language: node_js
node_js:
  - '0.8'
  - '0.10'

before_install:
  - npm install -g yo
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-panda' ]; then cd .. && eval "mv $currentfolder generator-panda" && cd generator-panda; fi

script:
  - npm install -g generator-panda
  - yo panda
  - n

notifications:
  emails:
    - abdonwww@gmail.com
  on_success: always # default: change
  on_failure: always
